// <auto-generated />
namespace Face.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class add_kaoQin : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_kaoQin));
        
        string IMigrationMetadata.Id
        {
            get { return "202006060906134_add_kaoQin"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
