// <auto-generated />
namespace Face.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class addeqnumsdt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addeqnumsdt));
        
        string IMigrationMetadata.Id
        {
            get { return "202005181314543_add-eqnum-sdt"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
