// <auto-generated />
namespace Face.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class addteacher : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addteacher));
        
        string IMigrationMetadata.Id
        {
            get { return "202004301027049_addteacher"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
